// Per-unit derivations — every key formula derived from first principles
// with each step's reasoning explained. Loaded at runtime by script.js and
// injected as a "Derivations" section between Key Equations and Diagram.

(function () {
  const D = (name, what, why, steps, result, valid) => `
<details class="derivation"><summary><span class="derivation-pill">Derivation</span> ${name}</summary>
<p><strong>What it says:</strong> ${what}</p>
<p><strong>Why we derive it:</strong> ${why}</p>
${steps.map(s => `<div class="step"><p>${s[0]}</p><span class="why">${s[1]}</span></div>`).join('')}
<p><strong>Result:</strong> $$${result}$$ <strong>Valid when:</strong> ${valid}</p>
</details>`;

  const DERIVATIONS = {};

  // ============= UNIT 1 — Kinematics =============
  DERIVATIONS['unit-1'] = [
    D('General velocity from acceleration',
      'If $a(t)$ is known, velocity at time $t$ is the initial velocity plus the area under the $a(t)$ curve.',
      'Acceleration is rarely constant; we need a tool that turns any $a(t)$ into $v(t)$.',
      [['Start from the definition $a(t)=dv/dt$.', 'This is the only bridge between $a$ and $v$ — everything flows from this definition.'],
       ['Separate: $dv = a(t)\\,dt$.', 'Each tiny change in velocity is the (almost-constant) acceleration times the tiny time interval.'],
       ['Integrate from 0 to $t$: $\\int_{v_0}^{v(t)}dv = \\int_0^t a(t\')\\,dt\'$.', 'Summing infinitely many infinitesimal changes is what a definite integral does (FTC).'],
       ['LHS evaluates to $v(t)-v_0$.', 'Integrating $dv$ between two values of $v$ is just the net change.']],
      'v(t)=v_0+\\int_0^t a(t\')\\,dt\'',
      'Always — no assumption on $a(t)$.'),

    D('General position from velocity',
      'Position at time $t$ equals initial position plus the area under $v(t)$.',
      'Once $v(t)$ is known, we still need $x(t)$ — the ultimate kinematic goal.',
      [['Start from $v(t)=dx/dt$.', 'Definition of velocity as instantaneous rate of change of position.'],
       ['Separate: $dx = v(t)\\,dt$; integrate with $x(0)=x_0$.', 'Distance = rate × time, applied infinitesimally.']],
      'x(t)=x_0+\\int_0^t v(t\')\\,dt\'',
      'Always in 1D; no restriction on $v(t)$.'),

    D('Constant-acceleration velocity $v=v_0+at$',
      'When $a$ is constant, $v$ grows linearly with time.',
      'This is the default model for free fall and most intro problems — we want a closed form.',
      [['Start from general $v(t)=v_0+\\int_0^t a\\,dt\'$.', 'Specialize the general result.'],
       ['Pull constant $a$ out: $\\int_0^t a\\,dt\' = at$.', 'Constants pull outside integrals; $\\int_0^t dt\' = t$.']],
      'v=v_0+at',
      '$a$ is constant in magnitude and direction.'),

    D('Constant-acceleration position $x=x_0+v_0 t+\\tfrac12 at^2$',
      'Under constant $a$, position is a quadratic in $t$: linear $v_0 t$ term + quadratic $\\tfrac12 at^2$ correction.',
      'Needed for "when?" and "where?" questions.',
      [['Start from $x(t)=x_0+\\int_0^t v(t\')dt\'$.', 'General position formula.'],
       ['Substitute $v(t\')=v_0+at\'$.', 'Using the constant-$a$ velocity law we just derived.'],
       ['Split: $\\int_0^t(v_0+at\')dt\'=v_0 t + a\\cdot t^2/2$.', 'Integral of a sum = sum of integrals; $\\int_0^t t\'dt\' = t^2/2$.']],
      'x = x_0 + v_0 t + \\tfrac12 at^2',
      '$a$ is constant.'),

    D('Time-independent kinematic equation $v^2=v_0^2+2a\\Delta x$',
      'Relates speeds and displacement without time — key for stopping-distance problems.',
      'Many problems don\'t involve time; eliminating $t$ between the previous two equations yields this.',
      [['Solve $v=v_0+at$ for $t$: $t=(v-v_0)/a$.', 'Isolating $t$ to substitute into the position equation.'],
       ['Plug into $\\Delta x = v_0 t + \\tfrac12 a t^2$, simplify using $v^2-v_0^2=(v-v_0)(v+v_0)$.', 'Difference-of-squares collapses the expression beautifully.']],
      'v^2 = v_0^2 + 2a(x-x_0)',
      '$a$ is constant.'),

    D('Projectile range $R = v_0^2\\sin(2\\theta)/g$',
      'Horizontal distance for a projectile launched and landing at the same height.',
      'Quick answers for ballistic problems — maximum at $\\theta=45°$.',
      [['Components: $v_{0x}=v_0\\cos\\theta$, $v_{0y}=v_0\\sin\\theta$; $a_x=0$, $a_y=-g$.', 'Horizontal and vertical motions decouple.'],
       ['Find flight time from $y=0$: $t_f = 2v_0\\sin\\theta/g$.', 'Symmetric launch: $y$ returns to 0 at $t=0$ (launch) and $t_f$ (landing).'],
       ['Substitute: $R = v_{0x}t_f = 2v_0^2\\sin\\theta\\cos\\theta/g$.', 'Range = horizontal speed × flight time.'],
       ['Apply $2\\sin\\theta\\cos\\theta=\\sin(2\\theta)$.', 'Double-angle identity reveals maximum at $2\\theta=90°$, i.e. $\\theta=45°$.']],
      'R = \\frac{v_0^2\\sin(2\\theta)}{g}',
      'Same launch and landing height, no air resistance.'),
  ].join('');

  // ============= UNIT 2 — Dynamics =============
  DERIVATIONS['unit-2'] = [
    D('Newton\'s 2nd Law $\\vec F = d\\vec p/dt$ reduces to $m\\vec a$',
      'Net force equals rate of change of momentum; for constant mass this becomes $m\\vec a$.',
      'The momentum form is the fundamental version; $\\vec F=m\\vec a$ is only a special case.',
      [['Define $\\vec p = m\\vec v$.', 'Momentum = "quantity of motion" — scales with both mass and velocity.'],
       ['State the law: $\\vec F_{net}=d\\vec p/dt$.', 'Force defined by what causes momentum to change.'],
       ['Product rule: $d\\vec p/dt = (dm/dt)\\vec v + m(d\\vec v/dt)$.', 'Both $m$ and $\\vec v$ can be time-dependent.'],
       ['If $m$ constant, $dm/dt=0$: $\\vec F = m\\vec a$.', 'The rigid-body special case that students meet first.']],
      '\\vec F_{net} = \\frac{d\\vec p}{dt} \\xrightarrow{\\,m=\\text{const}\\,} m\\vec a',
      'Inertial frame; general form always holds, $m\\vec a$ needs constant mass.'),

    D('Normal force on an incline $N = mg\\cos\\theta$',
      'A block on a $\\theta$-incline experiences normal force $mg\\cos\\theta$.',
      '$N$ is not given — it must be deduced from the perpendicular equilibrium.',
      [['FBD: gravity $m\\vec g$ down, normal $\\vec N$ perpendicular to incline.', 'Normal force acts perpendicular to the contact surface.'],
       ['Rotate axes: $x$ along slope, $y$ perpendicular.', 'Aligning axes with motion cuts work in half.'],
       ['Gravity perpendicular component = $mg\\cos\\theta$.', 'The incline tilts the normal by $\\theta$ from vertical.'],
       ['Block stays on surface: $a_\\perp=0$, so $N - mg\\cos\\theta=0$.', 'Kinematic constraint: no acceleration into surface.']],
      'N = mg\\cos\\theta',
      'Block on non-accelerating incline with no extra perpendicular forces.'),

    D('Slipping threshold $\\tan\\theta = \\mu_s$',
      'Block slides when incline angle exceeds $\\arctan(\\mu_s)$.',
      'Tilting a ramp until it slides is how we measure $\\mu_s$.',
      [['At slip threshold: $f_s = \\mu_s N$.', 'Static friction reaches its maximum at impending slip.'],
       ['Along slope: $mg\\sin\\theta = f_s = \\mu_s mg\\cos\\theta$.', 'Down-slope gravity equals max upslope friction.'],
       ['Divide by $mg\\cos\\theta$: $\\tan\\theta = \\mu_s$.', 'Mass cancels — slip angle is an intrinsic property of the surface pair.']],
      '\\tan\\theta_{max} = \\mu_s',
      'Coulomb friction model; rigid block not tipping.'),

    D('Atwood machine $a = (m_2-m_1)g/(m_1+m_2)$',
      'Two masses over a massless pulley accelerate at the net weight divided by total mass.',
      'Template for every connected-body problem.',
      [['Assume $m_2>m_1$. Positive direction for each = its direction of motion.', 'Inextensible-string constraint forces shared scalar $a$.'],
       ['$T-m_1g = m_1 a$ (for $m_1$).', 'Tension up, weight down, Newton II along the motion.'],
       ['$m_2 g - T = m_2 a$ (for $m_2$).', 'Same mass, flipped-sign convention because $m_2$ moves down.'],
       ['Add both equations: $(m_2-m_1)g = (m_1+m_2)a$.', 'Adding eliminates $T$ — a standard trick.']],
      'a = \\frac{(m_2-m_1)g}{m_1+m_2}',
      'Massless string/pulley; no friction in pulley.'),

    D('Linear drag $v(t) = v_T(1-e^{-bt/m})$',
      'Falling with drag $F_d=bv$ produces exponential approach to $v_T=mg/b$.',
      'First realistic falling-body problem; introduces separable ODEs.',
      [['Newton II (down positive): $m\\,dv/dt = mg - bv$.', 'Gravity drives; drag opposes and grows with $v$.'],
       ['At terminal: $dv/dt=0 \\Rightarrow v_T = mg/b$.', 'Terminal means forces exactly balance.'],
       ['Rewrite: $dv/dt = (b/m)(v_T - v)$.', 'Shows driving quantity is the gap $v_T-v$ — hallmark of exponential approach.'],
       ['Separate: $dv/(v_T-v) = (b/m)dt$; integrate with $v(0)=0$.', 'Both sides integrate to elementary functions.'],
       ['$\\ln[v_T/(v_T-v)] = bt/m \\Rightarrow v(t) = v_T(1-e^{-bt/m})$.', 'Exponentiate to solve for $v$.']],
      'v(t)=\\frac{mg}{b}(1-e^{-bt/m})',
      'Linear drag (low Reynolds); starts from rest.'),

    D('Conical pendulum $T = 2\\pi\\sqrt{L\\cos\\theta/g}$',
      'Mass swinging in horizontal circle at angle $\\theta$ from vertical.',
      'Combines circular motion, FBDs, and geometric constraints.',
      [['FBD: tension along string, gravity down. Radius $r=L\\sin\\theta$.', 'String can only pull; $r$ from geometry.'],
       ['Vertical: $T_{ten}\\cos\\theta = mg$.', 'No vertical acceleration — horizontal circular path.'],
       ['Horizontal (centripetal): $T_{ten}\\sin\\theta = m\\omega^2 r$.', 'Horizontal component of tension supplies $m\\omega^2 r$.'],
       ['Divide: $\\tan\\theta = \\omega^2 r/g = \\omega^2 L\\sin\\theta/g$.', 'Dividing eliminates unknown $T_{ten}$.'],
       ['Cancel $\\sin\\theta$: $\\omega^2 = g/(L\\cos\\theta)$; $T = 2\\pi/\\omega$.', 'Period depends on vertical drop $L\\cos\\theta$, not string length directly.']],
      'T = 2\\pi\\sqrt{\\frac{L\\cos\\theta}{g}}',
      'Inextensible massless string; steady horizontal circle.'),
  ].join('');

  // ============= UNIT 3 — Work/Energy =============
  DERIVATIONS['unit-3'] = [
    D('Work as a line integral $W=\\int\\vec F\\cdot d\\vec r$',
      'Work is the integral of the force component parallel to displacement.',
      '"Force times distance" fails for curved paths or varying forces.',
      [['Only the component of $\\vec F$ along $d\\vec r$ transfers energy.', 'Perpendicular forces (normal, centripetal) do no work — that\'s the geometric content of the dot product.'],
       ['For constant $\\vec F$ along straight $\\vec d$: $W = \\vec F\\cdot\\vec d = Fd\\cos\\theta$.', '$\\cos\\theta$ projects $\\vec F$ onto $\\vec d$.'],
       ['For variable $\\vec F$: $dW=\\vec F\\cdot d\\vec r$; integrate along path.', 'Riemann-sum idea: break path into pieces where $\\vec F$ is effectively constant.']],
      'W = \\int_A^B \\vec F\\cdot d\\vec r',
      'Always — this is the definition of mechanical work.'),

    D('Work–energy theorem $W_{net} = \\Delta K$, with $K=\\tfrac12 mv^2$',
      'Net work equals change in kinetic energy.',
      'Converts Newton II (instantaneous) into an energy law (integral) — often much easier.',
      [['Start from $F_{net} = m\\,dv/dt$.', 'Newton II in 1D.'],
       ['Chain rule: $dv/dt = v\\,dv/dx$.', 'Key move — trades time for position.'],
       ['So $F_{net}\\,dx = mv\\,dv$; integrate both sides.', 'Both are exact differentials.'],
       ['$\\int F_{net}dx = \\int mv\\,dv = \\tfrac12 mv_f^2 - \\tfrac12 mv_i^2$.', 'Left side is $W_{net}$ by definition; right gives $K$ naturally.']],
      'W_{net} = \\tfrac12 mv_f^2 - \\tfrac12 mv_i^2',
      'Non-relativistic speeds, constant mass.'),

    D('$F = -dU/dx$ (conservative force from potential energy)',
      'Conservative force = negative spatial derivative of its potential.',
      '$U$ is a scalar — far easier than vector $\\vec F$.',
      [['Define: $W_{cons} = -\\Delta U$ for some scalar $U(x)$.', 'Minus sign chosen so $U$ decreases when force does positive work (ball falling).'],
       ['For a small step $dx$: $dW = F\\,dx$ and $dW = -dU$.', 'Both describe the same energy transfer.'],
       ['Equate: $F = -dU/dx$. In 3D: $\\vec F = -\\nabla U$.', 'Force points "downhill" on the $U$ curve.']],
      'F_x = -\\frac{dU}{dx}',
      'Force is conservative (path-independent work).'),

    D('Gravitational PE $U=-GMm/r$',
      'Universal gravitational PE relative to infinity.',
      '$mgy$ fails at astronomical scales; we need a form that handles $1/r^2$ force.',
      [['Force: $\\vec F = -GMm\\hat r/r^2$ (attractive, toward $M$).', 'Newton\'s law of gravitation.'],
       ['$U(r) - U(\\infty) = -\\int_\\infty^r \\vec F\\cdot d\\vec r = \\int_\\infty^r (GMm/r\'^2)dr\'$.', 'Integrate force from reference ($\\infty$) inward.'],
       ['Evaluate: $U(r) = GMm[-1/r\']_\\infty^r = -GMm/r$ (since $1/\\infty=0$).', 'Infinity is natural reference because $1/r\\to 0$ there.']],
      'U(r) = -\\frac{GMm}{r}',
      'Point masses (or spherical bodies); $U(\\infty)=0$.'),

    D('Spring PE $U = \\tfrac12 kx^2$',
      'Elastic PE stored in an ideal spring.',
      'Archetype of a quadratic well; every small-oscillation system reduces to this.',
      [['Hooke\'s law: $F = -kx$ (restoring).', 'Minus sign makes the force always point back toward equilibrium.'],
       ['$U(x) - U(0) = -\\int_0^x F\\,dx\' = \\int_0^x kx\'\\,dx\' = \\tfrac12 kx^2$.', 'Choosing $U(0)=0$ at equilibrium is the natural convention.'],
       ['Check: $F = -dU/dx = -kx$ ✓.', 'Consistency with Hooke\'s law.']],
      'U(x) = \\tfrac12 kx^2',
      'Ideal Hookean spring (below elastic limit).'),

    D('Power $P = \\vec F\\cdot\\vec v$',
      'Instantaneous power = dot product of force and velocity.',
      'Engines are rated in horsepower, not joules.',
      [['Define: $P = dW/dt$.', 'Energy per second — the time-rate of doing work.'],
       ['$dW = \\vec F\\cdot d\\vec r$, so $P = \\vec F\\cdot d\\vec r/dt = \\vec F\\cdot\\vec v$.', 'Why a car\'s top speed is limited: higher $v$ means smaller available $F$ at fixed $P$.']],
      'P = \\vec F\\cdot\\vec v',
      'Always — definitional time derivative of work.'),

    D('Escape speed $v_{esc} = \\sqrt{2GM/R}$',
      'Minimum launch speed to reach infinity with zero leftover speed.',
      'Sets threshold between bound and unbound trajectories.',
      [['Total energy at launch: $E_i = \\tfrac12 m v_{esc}^2 - GMm/R$.', 'KE + universal PE.'],
       ['At infinity with $v_\\infty=0$: $E_f = 0$.', '"Just barely" escape: zero speed left at infinity.'],
       ['Conserve energy: $\\tfrac12 m v_{esc}^2 = GMm/R$.', 'No dissipation along the way.'],
       ['Solve: $v_{esc}^2 = 2GM/R$.', 'Mass cancels — escape speed same for bullet or boulder.']],
      'v_{esc} = \\sqrt{\\frac{2GM}{R}}',
      'No drag, single-body gravity, non-relativistic.'),
  ].join('');

  // ============= UNIT 4 — Momentum =============
  DERIVATIONS['unit-4'] = [
    D('Impulse–momentum $\\vec J = \\int\\vec F\\,dt = \\Delta\\vec p$',
      'Integral of force over time equals change in momentum.',
      'Collisions have huge brief forces — we rarely know $F(t)$ but need to relate its integral to $\\Delta p$.',
      [['Start from $\\vec F_{net} = d\\vec p/dt$.', 'General Newton II.'],
       ['Separate: $\\vec F_{net}\\,dt = d\\vec p$.', 'Both sides ready to integrate.'],
       ['Integrate: $\\int_{t_i}^{t_f}\\vec F_{net}\\,dt = \\vec p_f - \\vec p_i$.', 'Sum infinitesimal pushes over the interaction.']],
      '\\vec J = \\int_{t_i}^{t_f}\\vec F\\,dt = \\Delta\\vec p',
      'Any single particle with well-defined net force.'),

    D('Conservation of momentum',
      'If no external force acts, total momentum is constant.',
      'Master tool for collisions/explosions — internal forces are complicated but irrelevant to $\\vec p_{total}$.',
      [['$\\vec P = \\sum_i \\vec p_i$; differentiate: $d\\vec P/dt = \\sum_i d\\vec p_i/dt = \\sum \\vec F_i$.', 'System momentum is vector sum.'],
       ['Split: $\\vec F_i = \\vec F_i^{ext} + \\sum_{j\\ne i} \\vec F_{ji}$.', 'External and internal parts.'],
       ['Internal forces cancel pairwise (Newton III): $\\vec F_{ji} = -\\vec F_{ij}$.', 'Every internal action has equal opposite reaction within the system.'],
       ['So $d\\vec P/dt = \\vec F_{ext,net}$. If zero, $\\vec P$ is constant.', 'Only external forces can change system momentum.']],
      '\\vec F_{ext} = 0 \\Rightarrow \\vec P = \\text{const}',
      'Closed system; for axis-only conservation use only that component.'),

    D('Perfectly inelastic collision $v_f = (m_1 v_1+m_2 v_2)/(m_1+m_2)$',
      'Objects stick together; maximum KE loss consistent with momentum conservation.',
      'Starting point for every stick-together problem.',
      [['No external impulse: $P_i = P_f$.', 'Collisions are brief; external forces negligible over $\\Delta t$.'],
       ['Initial: $P_i = m_1 v_1 + m_2 v_2$.', 'Sum of individual momenta.'],
       ['Stick condition: $v_1\' = v_2\' = v_f$.', 'Defining constraint of "perfectly inelastic."'],
       ['Set $P_i = (m_1+m_2)v_f$ and solve.', 'Combined mass moves at single velocity.']],
      'v_f = \\frac{m_1 v_1+m_2 v_2}{m_1+m_2}',
      'Isolated system; objects coalesce.'),

    D('Elastic collision with target at rest',
      '$v_1\' = (m_1-m_2)v_1/(m_1+m_2)$ and $v_2\' = 2m_1 v_1/(m_1+m_2)$.',
      'Elastic needs BOTH momentum and KE conservation — two equations, two unknowns.',
      [['Momentum: $m_1 v_1 = m_1 v_1\' + m_2 v_2\'$.', 'Always conserved.'],
       ['KE: $\\tfrac12 m_1 v_1^2 = \\tfrac12 m_1 v_1\'^2 + \\tfrac12 m_2 v_2\'^2$.', 'Elastic: no energy lost to heat/deformation.'],
       ['Factor KE with difference of squares, divide by momentum: $v_1 + v_1\' = v_2\'$.', 'Relative velocity reverses — elegant elastic identity.'],
       ['Substitute back and solve the linear system.', 'Simplifies to standard target-at-rest formulas.']],
      'v_1\' = \\frac{m_1-m_2}{m_1+m_2}v_1,\\quad v_2\' = \\frac{2m_1}{m_1+m_2}v_1',
      '1D elastic, target at rest.'),

    D('Center of mass $\\vec r_{cm} = (1/M)\\int\\vec r\\,dm$',
      'Mass-weighted average position.',
      'Single point that moves as if all mass and force were concentrated there.',
      [['Discrete: $\\vec r_{cm} = (\\sum m_i\\vec r_i)/M$.', 'Natural weighted average.'],
       ['Continuous: take Riemann limit, $\\vec r_{cm} = (1/M)\\int\\vec r\\,dm$.', 'Standard discrete-to-continuous transition.'],
       ['With density: $dm=\\rho\\,dV$.', 'Makes integrals computable.']],
      '\\vec r_{cm} = \\frac{1}{M}\\int\\vec r\\,dm',
      'Any well-defined mass distribution.'),

    D('CM theorem $\\vec F_{ext} = M\\vec a_{cm}$',
      'Net external force equals total mass times CM acceleration.',
      'Lets us treat any extended body as a point particle for translational motion.',
      [['$M\\vec r_{cm} = \\sum m_i\\vec r_i$; differentiate twice.', '$M$ constant for closed system.'],
       ['$M\\vec a_{cm} = d\\vec P/dt = \\vec F_{ext,net}$.', 'Internal forces cancel; only external remain.']],
      '\\vec F_{ext} = M\\vec a_{cm}',
      'Closed system; holds even if internal parts accelerate wildly.'),
  ].join('');

  // ============= UNIT 5 — Rotation =============
  DERIVATIONS['unit-5'] = [
    D('Torque $\\vec\\tau = \\vec r\\times\\vec F$',
      'Torque magnitude = lever arm × perpendicular force component.',
      'Rotation depends on tangential force and lever arm; we need magnitude AND axis.',
      [['Decompose $\\vec F$ into radial and tangential components.', 'Only tangential $F_\\perp$ produces angular acceleration.'],
       ['Magnitude $\\tau = rF\\sin\\theta$.', '$F\\sin\\theta$ is the tangential piece; $r$ is the lever arm.'],
       ['Direction by RHR — perpendicular to plane of $\\vec r$ and $\\vec F$.', 'Magnitude $rF\\sin\\theta$ + perpendicular axis exactly define a cross product.']],
      '\\vec\\tau = \\vec r\\times\\vec F',
      '$\\vec r$ from chosen pivot; force applied at that point.'),

    D('Rotational Newton II: $\\Sigma\\tau = I\\alpha$',
      'Net torque = moment of inertia × angular acceleration.',
      'Rotational analog of $\\vec F=m\\vec a$; solves every rigid-body problem.',
      [['For each particle: $\\vec r_i\\times\\vec F_i = \\vec r_i\\times m_i\\vec a_i$.', 'Newton II applied particle-by-particle.'],
       ['Sum; internal Newton-III pairs cancel torques (forces along line joining pair).', 'Only external torques survive.'],
       ['Rigid rotation: $|\\vec r_i\\times m_i\\vec a_i| = m_i r_i^2\\alpha$ (tangential); radial gives zero.', 'All particles share same $\\alpha$.'],
       ['Sum: $\\tau_{net} = (\\sum m_i r_i^2)\\alpha = I\\alpha$.', 'Defines moment of inertia $I$.']],
      '\\Sigma\\tau = I\\alpha',
      'Rigid body, fixed axis (or through CM).'),

    D('Parallel-axis theorem $I = I_{cm} + Md^2$',
      'Moment about any axis = moment about parallel CM axis + $Md^2$.',
      'Avoids re-integrating when axis is displaced.',
      [['Let $\\vec r = \\vec r_{cm}\' + \\vec d$ (2D perpendicular coords).', '$\\vec r_{cm}\'$ from CM axis; $\\vec d$ from CM axis to new axis.'],
       ['$r^2 = r_{cm}\'^2 + 2\\vec r_{cm}\'\\cdot\\vec d + d^2$; integrate.', 'Expand the dot product.'],
       ['Middle term vanishes: $\\int\\vec r_{cm}\'\\,dm = 0$ by definition of CM.', 'The "vanishing" step is the heart of the theorem.']],
      'I = I_{cm} + Md^2',
      'Parallel axes; $d$ = perpendicular distance between them.'),

    D('Rolling constraint $v_{cm} = R\\omega$',
      'No-slip rolling wheel: CM speed equals radius × angular speed.',
      'Links rotational and translational variables.',
      [['In $dt$ the wheel turns $d\\theta$; arc laid down $ds = R\\,d\\theta$.', 'Definition of radian.'],
       ['No slip: contact point at rest means $dx_{cm} = ds$.', 'Arc laid = CM displaced.'],
       ['Divide by $dt$: $v_{cm} = R\\omega$. Differentiate again: $a_{cm}=R\\alpha$.', 'Same constraint at all orders.']],
      'v_{cm} = R\\omega,\\quad a_{cm} = R\\alpha',
      'Rolling without slipping.'),

    D('Moment of inertia of uniform rod about center $= ML^2/12$',
      'Thin uniform rod rotated through its center.',
      'Standard reference result; classic 1D integration.',
      [['$\\lambda = M/L$; slice of width $dx$ has $dm = \\lambda\\,dx$, distance $|x|$.', 'Symmetric limits $x\\in[-L/2, L/2]$.'],
       ['$I = \\int_{-L/2}^{L/2} x^2\\lambda\\,dx = \\lambda\\cdot L^3/12$.', 'Power rule $\\int x^2 dx = x^3/3$.'],
       ['$I = (M/L)\\cdot L^3/12 = ML^2/12$.', 'Eliminate density in favor of mass.']],
      'I_{rod,center} = \\tfrac{1}{12}ML^2',
      'Thin uniform rod about perpendicular center axis.'),

    D('Solid disk about central axis $= \\tfrac12 MR^2$',
      'Uniform disk about its symmetry axis.',
      'Standard wheel/pulley/flywheel model.',
      [['Rings: each of radius $r$, thickness $dr$; $dm = \\sigma\\cdot 2\\pi r\\,dr$.', 'All points on a ring at same $r$.'],
       ['$dI = r^2\\,dm = 2\\pi\\sigma r^3\\,dr$.', 'Every particle on ring at distance $r$.'],
       ['Integrate: $I = 2\\pi\\sigma R^4/4 = \\pi\\sigma R^4/2$.', 'Power rule on $r^3$.'],
       ['Substitute $\\sigma = M/\\pi R^2$: $I = \\tfrac12 MR^2$.', 'Eliminate density.']],
      'I_{disk} = \\tfrac12 MR^2',
      'Uniform solid disk (or cylinder) about central axis.'),

    D('Solid sphere about diameter $= \\tfrac25 MR^2$',
      'Uniform ball about any diameter.',
      'Essential for rolling-ball problems.',
      [['Stack of thin disks at height $z\\in[-R,R]$; each has radius $y=\\sqrt{R^2-z^2}$.', '3D → stack of known disks.'],
       ['$dm = \\rho\\pi y^2\\,dz$; $dI_{slab} = \\tfrac12 y^2\\,dm$.', 'Each slab is a disk about the same axis.'],
       ['$I = (\\pi\\rho/2)\\int_{-R}^R(R^2-z^2)^2 dz = (\\pi\\rho/2)(16R^5/15)$.', 'Expand polynomial and integrate.'],
       ['Substitute $\\rho = 3M/(4\\pi R^3)$: $I = \\tfrac25 MR^2$.', 'Eliminate density.']],
      'I_{sphere} = \\tfrac25 MR^2',
      'Uniform solid sphere about any diameter.'),
  ].join('');

  // ============= UNIT 6 — Rot energy/L =============
  DERIVATIONS['unit-6'] = [
    D('Rotational KE $= \\tfrac12 I\\omega^2$',
      'Rigid-body rotational kinetic energy.',
      '$I$ emerges as the rotational analog of mass.',
      [['$K = \\sum\\tfrac12 m_i v_i^2$.', 'Sum KE over all particles.'],
       ['Rigid: $v_i = \\omega r_i$, so $K = \\tfrac12\\omega^2\\sum m_i r_i^2 = \\tfrac12 I\\omega^2$.', '$\\omega$ same for all particles; the sum is $I$.']],
      'K_{rot} = \\tfrac12 I\\omega^2',
      'Rigid rotation about a fixed axis.'),

    D('Rolling KE $= \\tfrac12 Mv_{cm}^2 + \\tfrac12 I_{cm}\\omega^2$',
      'Translation + rotation about CM.',
      'Huge simplification: split motion into two independent pieces.',
      [['Decompose: $\\vec v_i = \\vec v_{cm} + \\vec v_i\'$.', 'Galilean split.'],
       ['Square and sum: $K = \\tfrac12 Mv_{cm}^2 + \\sum m_i\\vec v_{cm}\\cdot\\vec v_i\' + \\tfrac12\\sum m_i v_i\'^2$.', 'Expand $|\\vec v_{cm}+\\vec v_i\'|^2$.'],
       ['Cross term vanishes: $\\sum m_i\\vec v_i\' = 0$ (CM frame has zero momentum).', 'By definition of CM frame.'],
       ['Last term = $\\tfrac12 I_{cm}\\omega^2$ (pure rotation about CM).', 'In CM frame, rigid body only rotates.']],
      'K = \\tfrac12 Mv_{cm}^2 + \\tfrac12 I_{cm}\\omega^2',
      'Rigid body; rolling adds constraint $v_{cm}=R\\omega$.'),

    D('Angular momentum: $\\vec L=\\vec r\\times\\vec p$ and $L=I\\omega$',
      'Rotational analog of linear momentum.',
      'Gives $\\tau_{ext}=dL/dt$ — the rotational version of Newton II.',
      [['Particle: $\\vec L = \\vec r\\times\\vec p = m\\vec r\\times\\vec v$.', 'Definition; its derivative will yield torque.'],
       ['Rigid body, fixed axis: $v_i = \\omega r_i$, contribution $L_z = m_i r_i^2\\omega$.', 'Pure tangential velocity; cross product = $r_i v_i\\sin 90°$.'],
       ['Sum: $L_z = \\omega\\sum m_i r_i^2 = I\\omega$.', 'Same $I$ as in rotational KE.']],
      '\\vec L = \\vec r\\times\\vec p;\\quad L = I\\omega',
      '$L=I\\omega$ needs rotation about a principal axis.'),

    D('$\\tau_{ext} = dL/dt$',
      'Net external torque equals rate of change of total angular momentum.',
      'Rotational Newton II; drives all rotational dynamics.',
      [['$\\vec L = \\sum\\vec r_i\\times\\vec p_i$; differentiate with product rule.', 'Cross products obey product rule.'],
       ['First term: $\\vec v_i\\times\\vec p_i = m_i\\vec v_i\\times\\vec v_i = 0$.', 'Cross product of vector with itself.'],
       ['Second term: $\\vec r_i\\times(d\\vec p_i/dt) = \\vec r_i\\times\\vec F_i = \\vec\\tau_i$.', 'Newton II per particle.'],
       ['Internal torques cancel (forces along joining line): only $\\tau_{ext}$ remains.', 'Third-law pairs produce zero net torque.']],
      '\\tau_{ext} = \\frac{dL}{dt}',
      'Origin is inertial or CM; internal forces are central.'),

    D('Orbital speed $v = \\sqrt{GM/r}$ (circular orbit)',
      'Circular orbit speed derived from gravity as centripetal.',
      'Gravity provides exactly the centripetal force needed.',
      [['Circular motion requires $F_c = mv^2/r$.', 'Kinematic demand.'],
       ['Gravity supplies: $GMm/r^2 = mv^2/r$.', 'Both point toward center.'],
       ['Cancel $m$ and one $r$: $v^2 = GM/r$.', 'Satellite mass drops out — orbital speed is universal.']],
      'v = \\sqrt{\\frac{GM}{r}}',
      'Circular orbit, $M\\gg m$, no other forces.'),

    D('Kepler III $T^2 = 4\\pi^2 r^3/(GM)$',
      'Period squared proportional to radius cubed.',
      'Links timing ($T$) to geometry ($r$) for any orbit.',
      [['$T = 2\\pi r/v$ for circular orbit.', 'Circumference/speed.'],
       ['Substitute $v = \\sqrt{GM/r}$: $T = 2\\pi\\sqrt{r^3/GM}$.', 'Uses previous derivation.'],
       ['Square: $T^2 = 4\\pi^2 r^3/GM$.', 'Kepler III — same constant for all bodies around same primary.']],
      'T^2 = \\frac{4\\pi^2 r^3}{GM}',
      'Circular orbit; for ellipses, replace $r$ by $a$.'),

    D('Total orbit energy $E = -GMm/(2r)$',
      'Bound orbit energy — negative and half the PE magnitude.',
      'Virial result; shows bound orbits have $E<0$.',
      [['$K = \\tfrac12 mv^2 = GMm/(2r)$ using $v^2 = GM/r$.', 'Plug orbital speed into KE.'],
       ['$U = -GMm/r$ (universal PE).', 'Reference at infinity.'],
       ['$E = K + U = GMm/(2r) - GMm/r = -GMm/(2r)$.', 'Common denominator.']],
      'E = -\\frac{GMm}{2r}',
      'Circular orbit.'),
  ].join('');

  // ============= UNIT 7 — Oscillations =============
  DERIVATIONS['unit-7'] = [
    D('SHM ODE $\\ddot x = -\\omega^2 x$',
      'Mass on ideal spring obeys this second-order ODE.',
      'Defining equation of SHM; every oscillator reduces to it near a minimum.',
      [['Hooke: $F = -kx$; restoring, linear.', '$x$ from equilibrium; minus sign is the key.'],
       ['Newton II: $m\\ddot x = -kx$.', 'Spring is the only horizontal force.'],
       ['Divide: $\\ddot x = -(k/m)x$; define $\\omega^2 \\equiv k/m$.', 'Relabeling reveals canonical form.']],
      '\\ddot x = -\\omega^2 x',
      'Linear restoring force.'),

    D('General solution $x(t) = A\\cos(\\omega t + \\varphi)$',
      'Sinusoidal motion with amplitude $A$, phase $\\varphi$.',
      'Gives a closed-form trajectory and identifies $\\omega$ as angular frequency.',
      [['Guess $x = A\\cos(\\omega t + \\varphi)$.', 'Cosines are candidates because $d^2/dt^2$ returns a negative multiple of themselves.'],
       ['$\\ddot x = -A\\omega^2\\cos(\\omega t + \\varphi) = -\\omega^2 x$. ✓', 'Substitutes back into ODE identically.'],
       ['Two constants $A, \\varphi$ fit two ICs $x(0), \\dot x(0)$.', 'Second-order ODE needs two arbitrary constants.']],
      'x(t) = A\\cos(\\omega t + \\varphi)',
      'Motion obeys SHM ODE.'),

    D('Simple pendulum period $T = 2\\pi\\sqrt{L/g}$',
      'Point mass on massless string, small swings.',
      'Converts gravity-driven angular motion into SHM.',
      [['Torque: $\\tau = -MgL\\sin\\theta$ (restoring).', 'Tangential gravity component × lever arm $L$.'],
       ['$I\\ddot\\theta = \\tau$ with $I = ML^2$.', 'Point mass at distance $L$.'],
       ['Simplify: $\\ddot\\theta = -(g/L)\\sin\\theta$.', 'Not SHM yet — has $\\sin\\theta$.'],
       ['Small-angle: $\\sin\\theta\\approx\\theta$ → $\\ddot\\theta = -(g/L)\\theta$.', 'Linearizes to SHM form.'],
       ['Identify $\\omega^2 = g/L$; $T = 2\\pi/\\omega$.', 'Standard SHM read-off.']],
      'T = 2\\pi\\sqrt{\\frac{L}{g}}',
      'Small angles (<15°); massless inextensible string.'),

    D('Physical pendulum $T = 2\\pi\\sqrt{I/(Mgd)}$',
      'Rigid body pivoted at distance $d$ from CM.',
      'Generalizes simple pendulum to extended bodies.',
      [['$\\tau = -Mgd\\sin\\theta$ (gravity at CM, lever arm $d\\sin\\theta$).', 'Standard torque for offset weight.'],
       ['$I\\ddot\\theta = -Mgd\\sin\\theta$.', '$I$ about PIVOT (use parallel-axis).'],
       ['Small-angle: $\\ddot\\theta = -(Mgd/I)\\theta$.', 'Linearize.'],
       ['$\\omega^2 = Mgd/I$.', 'Period follows.']],
      'T = 2\\pi\\sqrt{\\frac{I}{Mgd}}',
      'Rigid body, small angles.'),

    D('Total SHM energy $E = \\tfrac12 kA^2$',
      'Sum of KE and PE is constant amplitude-squared.',
      'Energy conservation pinpoints speed at any $x$.',
      [['$U = \\tfrac12 kA^2\\cos^2(\\omega t + \\varphi)$.', 'Plug solution into $\\tfrac12 kx^2$.'],
       ['$K = \\tfrac12 mA^2\\omega^2\\sin^2(\\omega t + \\varphi) = \\tfrac12 kA^2\\sin^2$.', 'Using $m\\omega^2 = k$.'],
       ['$E = K + U = \\tfrac12 kA^2(\\sin^2+\\cos^2) = \\tfrac12 kA^2$.', 'Pythagorean identity kills time dependence.']],
      'E = \\tfrac12 kA^2 = \\tfrac12 mv^2 + \\tfrac12 kx^2',
      'No damping.'),

    D('Taylor expansion $\\Rightarrow k_{eff} = U\'\'(x_0)$',
      'Any smooth potential looks parabolic near a stable minimum.',
      'Explains why SHM is universal.',
      [['Taylor: $U(x) = U(x_0) + U\'(x_0)(x-x_0) + \\tfrac12 U\'\'(x_0)(x-x_0)^2 + \\cdots$', 'Standard expansion.'],
       ['At equilibrium, $U\'(x_0)=0$.', 'Zero force means zero slope of $U$.'],
       ['Drop constant: $U \\approx \\tfrac12 U\'\'(x_0)\\xi^2$.', 'Leading nontrivial term is quadratic.'],
       ['$F = -dU/d\\xi = -U\'\'(x_0)\\xi$. Match Hooke\'s: $k_{eff} = U\'\'(x_0)$.', 'Needs $U\'\'(x_0) > 0$ (true minimum).']],
      'k_{eff} = U\'\'(x_0),\\quad \\omega = \\sqrt{U\'\'(x_0)/m}',
      'Stable minimum; small displacements.'),
  ].join('');

  // ============= UNIT 8 — Gauss =============
  DERIVATIONS['unit-8'] = [
    D('Coulomb\'s law $F = kq_1 q_2/r^2$',
      'Force between two point charges is inverse-square.',
      'Experimental foundation — every electrostatics result rests here.',
      [['Coulomb\'s torsion balance: $F\\propto q_1 q_2$ and $F\\propto 1/r^2$.', 'Direct measurement.'],
       ['Combine: $F = k q_1 q_2/r^2$.', 'One constant absorbs units.'],
       ['SI convention: $k = 1/(4\\pi\\varepsilon_0)$.', '$4\\pi$ inserted so Gauss\'s law has no stray factors.']],
      '\\vec F = \\frac{1}{4\\pi\\varepsilon_0}\\frac{q_1 q_2}{r^2}\\hat r',
      'Point charges at rest in vacuum.'),

    D('Gauss\'s law $\\oint\\vec E\\cdot d\\vec A = Q_{enc}/\\varepsilon_0$',
      'Net flux through any closed surface = enclosed charge / $\\varepsilon_0$.',
      'Converts Coulomb\'s law into a powerful tool for problems with symmetry.',
      [['Point charge at sphere\'s center: $E = kq/r^2$.', 'Coulomb on simplest surface.'],
       ['Flux: $\\Phi = E\\cdot 4\\pi r^2 = 4\\pi kq = q/\\varepsilon_0$.', 'The $r^2$ from area cancels $1/r^2$ — this cancellation is why inverse-square matters.'],
       ['Deform surface: flux depends only on solid angle $d\\Omega$, totaling $4\\pi$ for interior point.', '$\\int d\\Omega = 4\\pi$ for enclosed charge; 0 for exterior.'],
       ['Superposition: extends to arbitrary charge distributions.', 'Fields add linearly.']],
      '\\oint\\vec E\\cdot d\\vec A = \\frac{Q_{enc}}{\\varepsilon_0}',
      'Always true; solvable for $E$ only under high symmetry.'),

    D('Uniform insulating sphere: $E$ inside and outside',
      'Outside looks like point charge; inside $E\\propto r$.',
      'Showcases Gauss\'s law in both regions.',
      [['Spherical symmetry: $\\vec E$ radial, depends only on $r$.', 'Rotations leave distribution unchanged.'],
       ['Outside ($r\\ge R$): $E\\cdot 4\\pi r^2 = Q/\\varepsilon_0 \\Rightarrow E = kQ/r^2$.', 'All charge enclosed.'],
       ['Inside ($r<R$): $Q_{enc} = Q(r^3/R^3)$ (volume fraction).', 'Uniform $\\rho$; smaller sphere of radius $r$ encloses only the volume-fraction of $Q$.'],
       ['Plug in: $E = kQr/R^3$.', 'The $r^2$ in area partially cancels $r^3$ in $Q_{enc}$, leaving $r$.']],
      'E_{out}=\\frac{kQ}{r^2},\\quad E_{in}=\\frac{kQr}{R^3}',
      'Uniform insulator; continuous at $r=R$.'),

    D('Infinite line of charge $E = \\lambda/(2\\pi\\varepsilon_0 r)$',
      'Field of an infinite uniformly charged wire.',
      'Cylindrical-symmetry archetype; key for coaxial cables.',
      [['Symmetry: $\\vec E$ radial, depends only on $r$.', 'Translation along wire and rotation about it are symmetries.'],
       ['Gaussian cylinder radius $r$, length $L$; curved side only.', 'End caps have $\\vec E\\perp d\\vec A$.'],
       ['$E(2\\pi r L) = \\lambda L/\\varepsilon_0 \\Rightarrow E = \\lambda/(2\\pi\\varepsilon_0 r)$.', '$L$ cancels — result independent of chosen length.']],
      'E = \\frac{\\lambda}{2\\pi\\varepsilon_0 r}',
      'Infinite wire; $r$ much less than wire length.'),

    D('Infinite sheet $E = \\sigma/(2\\varepsilon_0)$',
      'Uniform field on each side of an infinite charged plane.',
      'Canonical uniform-field source; underlies parallel-plate capacitors.',
      [['Symmetry: $\\vec E\\perp$ sheet, same magnitude both sides.', 'Translations parallel to sheet and reflection through it.'],
       ['Gaussian pillbox: two flat caps + curved side.', 'Matches symmetry.'],
       ['Flux: $\\Phi = 2EA$ (both caps); $Q_{enc} = \\sigma A$.', 'Curved side contributes nothing ($\\vec E\\parallel$ wall).'],
       ['Gauss: $2EA = \\sigma A/\\varepsilon_0 \\Rightarrow E = \\sigma/(2\\varepsilon_0)$.', '$A$ cancels; $E$ uniform regardless of distance.']],
      'E = \\frac{\\sigma}{2\\varepsilon_0}',
      'Infinite non-conducting sheet.'),

    D('Conductor surface $E = \\sigma/\\varepsilon_0$',
      'Just outside a conductor in equilibrium, twice the sheet value.',
      'Distinguishes conductors from isolated sheets.',
      [['Inside conductor: $\\vec E = 0$.', 'Otherwise electrons would accelerate, violating equilibrium.'],
       ['Just outside: $\\vec E\\perp$ surface.', 'Tangential component would drive surface currents.'],
       ['Gaussian pillbox straddling surface: only outside cap contributes ($\\vec E=0$ inside).', 'Flux goes out only one side.'],
       ['$EA = \\sigma A/\\varepsilon_0 \\Rightarrow E = \\sigma/\\varepsilon_0$.', 'Factor of 2 bigger than isolated sheet because flux exits one side only.']],
      'E_{surface} = \\frac{\\sigma}{\\varepsilon_0}',
      'Conductor in electrostatic equilibrium.'),
  ].join('');

  // ============= UNIT 9 — Potential =============
  DERIVATIONS['unit-9'] = [
    D('Potential $V = U/q$',
      'Potential is PE per unit test charge.',
      'Defines a scalar field describing sources alone.',
      [['Work–energy: $W_{elec} = -\\Delta U$ for conservative electrostatic force.', 'Standard conservative-force relation.'],
       ['$\\vec F = q\\vec E$ → $U$ scales linearly with $q$.', '$\\vec E$ depends on sources only, not probe.'],
       ['Divide: $V = U/q$ is probe-independent.', 'Clean scalar field of the sources.']],
      'V = U/q',
      'Electrostatics; test charge small enough not to disturb sources.'),

    D('Point charge potential $V = kq/r$',
      'With reference $V(\\infty)=0$.',
      'Building block for superposition.',
      [['Use $V(r) - V(\\infty) = -\\int_\\infty^r \\vec E\\cdot d\\vec l$, with $\\vec E = kq/r^2\\hat r$.', 'Apply definition.'],
       ['Radial path: $V(r) = -\\int_\\infty^r (kq/r\'^2)dr\' = kq/r$.', 'Antiderivative of $1/r\'^2$ is $-1/r\'$; infinity term drops.']],
      'V(r) = \\frac{kq}{r}',
      'Point charge (or outside spherical distribution); $V(\\infty)=0$.'),

    D('$\\vec E = -\\nabla V$ (gradient relation)',
      'Electric field = negative gradient of potential.',
      'Inverts the line-integral relation — recovers $\\vec E$ from $V$.',
      [['For small displacement: $dV = -\\vec E\\cdot d\\vec l = -(E_x dx+E_y dy+E_z dz)$.', 'Shrink integration interval.'],
       ['Chain rule: $dV = (\\partial V/\\partial x)dx + (\\partial V/\\partial y)dy + (\\partial V/\\partial z)dz$.', 'Total differential.'],
       ['Match coefficients: $E_i = -\\partial V/\\partial x_i$.', 'Linear forms equal for all $d\\vec l$ have equal coefficients.']],
      '\\vec E = -\\nabla V',
      'Electrostatics; $V$ differentiable.'),

    D('PE of charge $U = qV$',
      'Placing charge $q$ where potential is $V$ stores energy $qV$.',
      'Inverse of the defining relation.',
      [['External work to carry $q$ from $\\infty$ to $P$ quasistatically: $W = q\\int_\\infty^P (-\\vec E)\\cdot d\\vec l = qV(P)$.', 'Quasistatic: no KE gained, $W_{ext}=\\Delta U$.'],
       ['So $U(P) = qV(P)$.', 'PE = reversible external work.']],
      'U = qV',
      'Sources unaffected by placing $q$; $V(\\infty)=0$.'),

    D('Assembly energy $U = \\sum_{i<j} kq_i q_j/r_{ij}$',
      'Build configuration charge-by-charge; sum pair energies.',
      'Standard energy bookkeeping rule with no double-counting.',
      [['First charge: $W_1 = 0$.', 'No existing sources to work against.'],
       ['Bring $q_2$ to distance $r_{12}$ from $q_1$: $W_2 = q_2 V_1 = kq_1 q_2/r_{12}$.', 'Use $U=qV$ with already-placed source.'],
       ['Continue: charge $j$ interacts with all $i<j$.', 'Restrict sum to $i<j$ to count each pair once.'],
       ['Sum: $U = \\sum_{i<j} kq_i q_j/r_{ij}$.', 'Order of assembly doesn\'t matter — final configuration has fixed energy.']],
      'U = \\sum_{i<j}\\frac{kq_i q_j}{r_{ij}}',
      'Point charges; $U=0$ at infinite separation.'),
  ].join('');

  // ============= UNIT 10 — Capacitors =============
  DERIVATIONS['unit-10'] = [
    D('Parallel-plate $C = \\varepsilon_0 A/d$',
      'Plates area $A$, gap $d$.',
      'Prototype capacitor.',
      [['Plates with $\\pm Q$ → $\\sigma = Q/A$ on inner faces.', 'Inner-face charge because conductors.'],
       ['Gauss pillbox enclosing one plate: $E = \\sigma/\\varepsilon_0 = Q/(\\varepsilon_0 A)$.', 'Conductor-surface result.'],
       ['$V = Ed = Qd/(\\varepsilon_0 A)$.', 'Uniform field.'],
       ['$C = Q/V = \\varepsilon_0 A/d$.', 'Geometry only.']],
      'C = \\frac{\\varepsilon_0 A}{d}',
      '$d\\ll\\sqrt A$ (fringing negligible).'),

    D('Spherical capacitor $C = 4\\pi\\varepsilon_0 ab/(b-a)$',
      'Concentric spheres radii $a<b$.',
      'Full spherical symmetry lets Gauss give $E$ cleanly.',
      [['Gauss: $E(r) = Q/(4\\pi\\varepsilon_0 r^2)$ between plates.', 'All $+Q$ enclosed.'],
       ['$V = \\int_a^b E\\,dr = (Q/4\\pi\\varepsilon_0)(1/a - 1/b) = (Q/4\\pi\\varepsilon_0)(b-a)/(ab)$.', 'Integrate $1/r^2$.'],
       ['$C = Q/V = 4\\pi\\varepsilon_0 ab/(b-a)$.', 'Limit $b\\to\\infty$ gives isolated-sphere $C = 4\\pi\\varepsilon_0 a$.']],
      'C = \\frac{4\\pi\\varepsilon_0 ab}{b-a}',
      'Concentric conducting spheres; vacuum.'),

    D('Cylindrical $C/L = 2\\pi\\varepsilon_0/\\ln(b/a)$',
      'Coaxial cylinders.',
      'Models coaxial cable.',
      [['Line-charge Gauss: $E = \\lambda/(2\\pi\\varepsilon_0 r)$ between.', 'Standard result.'],
       ['$V = \\int_a^b E\\,dr = (\\lambda/2\\pi\\varepsilon_0)\\ln(b/a)$.', '$\\int dr/r = \\ln r$.'],
       ['$\\lambda = Q/L$ → $V = Q\\ln(b/a)/(2\\pi\\varepsilon_0 L)$.', 'In terms of total charge.'],
       ['$C/L = 2\\pi\\varepsilon_0/\\ln(b/a)$.', 'Log is signature of cylindrical geometry.']],
      'C = \\frac{2\\pi\\varepsilon_0 L}{\\ln(b/a)}',
      '$L\\gg b$ so end effects negligible.'),

    D('Stored energy $U = \\tfrac12 CV^2$',
      'Work to charge a capacitor from 0 to $Q$.',
      'Links charging work to stored field energy.',
      [['At intermediate charge $q$, voltage is $v = q/C$.', '$C$ fixed by geometry.'],
       ['$dU = v\\,dq = (q/C)dq$.', 'Work to transfer next $dq$.'],
       ['Integrate: $U = \\int_0^Q q\\,dq/C = Q^2/(2C)$.', '$\\int q\\,dq = q^2/2$.'],
       ['Use $Q=CV$: $U = \\tfrac12 CV^2 = \\tfrac12 QV$.', '$\\tfrac12$ because voltage grew linearly 0→$V$ during charging.']],
      'U = \\tfrac12 CV^2 = \\frac{Q^2}{2C} = \\tfrac12 QV',
      'Quasistatic charging; linear capacitor.'),

    D('Energy density $u = \\tfrac12\\varepsilon_0 E^2$',
      'Energy per unit volume in any vacuum electric field.',
      'Localizes energy in the field rather than on charges.',
      [['Parallel plate: $U = \\tfrac12 CV^2 = \\tfrac12(\\varepsilon_0 A/d)(Ed)^2 = \\tfrac12\\varepsilon_0 E^2(Ad)$.', 'Substitute $C$, $V$.'],
       ['Volume containing field: $\\mathcal V = Ad$.', 'Field confined to the gap.'],
       ['$u = U/\\mathcal V = \\tfrac12\\varepsilon_0 E^2$.', 'Result contains only $E$ and $\\varepsilon_0$; generalizes to any field.']],
      'u = \\tfrac12\\varepsilon_0 E^2',
      'Vacuum; multiply by $\\kappa$ in dielectric.'),

    D('Series & parallel combinations',
      'Series: $1/C_{eq} = \\sum 1/C_i$. Parallel: $C_{eq} = \\sum C_i$.',
      'Opposite of resistor rules because capacitors relate Q to V differently.',
      [['Series: inner conductors isolated → same $Q$ on each.', 'Charge conservation on isolated islands.'],
       ['$V = \\sum V_i = Q\\sum 1/C_i$ → $1/C_{eq} = \\sum 1/C_i$.', 'Voltages add along a path.'],
       ['Parallel: same voltage → $Q_{tot} = V\\sum C_i$ → $C_{eq} = \\sum C_i$.', 'Charges add at a node.']],
      '\\text{series: }\\frac{1}{C_{eq}}=\\sum\\frac{1}{C_i};\\quad \\text{parallel: }C_{eq}=\\sum C_i',
      'Standard capacitor networks.'),
  ].join('');

  // ============= UNIT 11 — Circuits =============
  DERIVATIONS['unit-11'] = [
    D('Resistance $R = \\rho L/A$',
      'Resistance grows with length, shrinks with area.',
      'Lets you size wire for a target resistance.',
      [['Microscopic Ohm: $\\vec J = \\sigma\\vec E$ with $\\sigma = 1/\\rho$.', 'Drude-type result: drift velocity $\\propto E$.'],
       ['Uniform wire: $E = V/L$, $I = JA = \\sigma EA = VA/(\\rho L)$.', 'Combine $J = \\sigma E$ with $I = JA$.'],
       ['Solve: $R \\equiv V/I = \\rho L/A$.', 'Resistance = proportionality between $V$ and $I$.']],
      'R = \\frac{\\rho L}{A}',
      'Uniform material, steady current, constant $T$.'),

    D('Ohm\'s law $V = IR$',
      'For ohmic materials, $V \\propto I$.',
      'Workhorse of DC circuit analysis.',
      [['From $\\vec J = \\sigma\\vec E$: $I/A = \\sigma V/L$.', 'Empirical linear response.'],
       ['Solve: $V = I(L/\\sigma A) = IR$.', 'Geometry lumped into $R$.']],
      'V = IR',
      'Ohmic (linear) conductor. Fails for diodes, plasmas.'),

    D('Power $P = IV = I^2R = V^2/R$',
      'Rate of energy delivery.',
      'Explains resistor heating.',
      [['$dW = V\\,dq$ for charge crossing potential drop $V$.', 'Definition of potential.'],
       ['$P = dW/dt = VI$.', 'Using $I = dq/dt$.'],
       ['Substitute $V=IR$ or $I=V/R$.', 'Use whichever variable is known.']],
      'P = IV = I^2 R = V^2/R',
      '$P=IV$ always; others require ohmic $R$.'),

    D('Kirchhoff rules',
      'Junction: $\\sum I_{in} = \\sum I_{out}$. Loop: $\\sum\\Delta V = 0$.',
      'Turns any circuit into a solvable linear system.',
      [['Junction: steady state → no charge buildup at node.', 'Charge conservation.'],
       ['Loop: $\\oint\\vec E\\cdot d\\vec l = 0$ for electrostatic field.', 'Conservative field; no net work on a charge returning to start.']],
      '\\sum I_{in} = \\sum I_{out};\\quad \\sum\\Delta V_{loop} = 0',
      'Lumped circuits, no changing flux through loop.'),

    D('RC charging $q(t) = Q_f(1-e^{-t/RC})$',
      'Capacitor charge rises exponentially to $Q_f = C\\varepsilon$.',
      'Models all first-order RC responses.',
      [['Loop rule: $\\varepsilon - iR - q/C = 0$, with $i = dq/dt$.', 'KVL around the circuit.'],
       ['Rearrange: $R\\,dq/dt = (C\\varepsilon - q)/C$.', 'Isolate derivative.'],
       ['Separate: $dq/(Q_f - q) = dt/RC$, integrate with $q(0)=0$.', 'Standard separable form.'],
       ['Result: $\\ln[Q_f/(Q_f-q)] = t/RC$; exponentiate.', 'Gives exponential approach to $Q_f$.']],
      'q(t) = C\\varepsilon(1-e^{-t/RC}),\\quad \\tau = RC',
      'Constant $\\varepsilon$, ohmic $R$, ideal $C$, $q(0)=0$.'),

    D('RC discharge $q(t) = Q_0 e^{-t/RC}$',
      'Pre-charged capacitor decays exponentially through $R$.',
      'Describes how stored energy leaks out.',
      [['KVL, no battery: $q/C + IR = 0$; $I = -dq/dt$.', 'Capacitor drives current through $R$; $q$ decreases as $I$ flows.'],
       ['$R\\,dq/dt = -q/C$ → $dq/q = -dt/RC$.', 'Separate.'],
       ['Integrate: $q = Q_0 e^{-t/RC}$.', 'Standard exponential decay.']],
      'q(t) = Q_0 e^{-t/RC}',
      'Series RC with no EMF.'),
  ].join('');

  // ============= UNIT 12 — Magnetism =============
  DERIVATIONS['unit-12'] = [
    D('Lorentz force $\\vec F = q\\vec v\\times\\vec B$',
      'Force on moving charge in magnetic field.',
      'Experimental definition of $\\vec B$; rationalize the cross product.',
      [['Obs 1: $F=0$ at rest → $F\\propto v$.', 'Rules out any $q\\vec B$-only term.'],
       ['Obs 2: $F\\propto\\sin\\theta$ between $\\vec v$ and $\\vec B$, zero when parallel.', 'Exact angular dependence of cross product.'],
       ['Obs 3: $\\vec F\\perp\\vec v$ (magnetic does no work).', 'Perpendicularity is defining property of cross product.'],
       ['Obs 4: $F\\propto q$ with correct sign.', 'Fixes linear charge dependence.'],
       ['Combine: $\\vec F = q\\vec v\\times\\vec B$.', 'Tesla defined so the constant is 1.']],
      '\\vec F = q\\vec v\\times\\vec B',
      'Non-relativistic point charge.'),

    D('Circular motion radius $r = mv/(qB)$',
      'Charge moving $\\perp\\vec B$ circles.',
      'Mass spectrometers, cyclotrons use this.',
      [['$\\vec F\\perp\\vec v$ → speed constant → circular motion.', 'Constant-magnitude perpendicular force gives circles.'],
       ['$\\vec v\\perp\\vec B$: $qvB = mv^2/r$.', 'Centripetal equation.'],
       ['Solve: $r = mv/(qB)$.', 'One factor of $v$ cancels.']],
      'r = \\frac{mv}{qB}',
      '$\\vec v\\perp\\vec B$; uniform field.'),

    D('Cyclotron period $T = 2\\pi m/(qB)$',
      'Independent of speed.',
      'Why cyclotrons use fixed-frequency drives.',
      [['$T = 2\\pi r/v$.', 'Period of uniform circular motion.'],
       ['Substitute $r = mv/qB$: $T = 2\\pi m/(qB)$.', '$v$ cancels — speed independence.']],
      'T = \\frac{2\\pi m}{qB}',
      'Non-relativistic.'),

    D('$B$ around a long straight wire $= \\mu_0 I/(2\\pi r)$',
      'Ampère\'s law with circular loop.',
      'Foundation for all wire-field problems.',
      [['Cylindrical symmetry: $B$ constant on circle, tangent to it.', 'Wire invariant under rotation and translation.'],
       ['Choose circular Amperian loop: $\\oint\\vec B\\cdot d\\vec l = B(2\\pi r)$.', '$\\vec B\\parallel d\\vec l$.'],
       ['Enclosed current is $I$: $B(2\\pi r) = \\mu_0 I$.', 'Ampère\'s law.']],
      'B = \\frac{\\mu_0 I}{2\\pi r}',
      'Infinite wire; $r\\ll$ wire length.'),

    D('$B$ at center of circular loop $= \\mu_0 I/(2R)$',
      'Direct Biot–Savart integration.',
      'Ampère doesn\'t help — no convenient symmetry surface.',
      [['Every $d\\vec l\\perp\\hat r$ on the loop; $|d\\vec l\\times\\hat r| = d\\ell$.', 'Tangent perpendicular to radius.'],
       ['$dB = \\mu_0 I\\,d\\ell/(4\\pi R^2)$.', 'All magnitudes equal since $r = R$ constant.'],
       ['All $d\\vec B$ align along axis; integrate $\\int d\\ell = 2\\pi R$.', 'No vector cancellation.'],
       ['Total: $B = \\mu_0 I/(2R)$.', 'Clean Biot–Savart result.']],
      'B = \\frac{\\mu_0 I}{2R}',
      'At center of planar circular loop.'),

    D('Solenoid $B = \\mu_0 n I$',
      'Uniform interior field of long solenoid.',
      'Standard way to produce uniform $\\vec B$.',
      [['Symmetry: $\\vec B$ axial inside, $\\approx 0$ outside.', 'No monopoles + translational symmetry.'],
       ['Amperian rectangle: one side inside axial, opposite side outside, short sides perpendicular.', 'Tailored to known field structure.'],
       ['$\\oint\\vec B\\cdot d\\vec l = BL$ (only inside side contributes).', 'Others give zero.'],
       ['Enclosed: $nL$ turns × $I$ each. Ampère: $BL = \\mu_0 nLI$.', '$L$ cancels.']],
      'B = \\mu_0 nI',
      'Long tightly wound solenoid, far from ends.'),

    D('Force/length between parallel wires $= \\mu_0 I_1 I_2/(2\\pi d)$',
      'Attractive for parallel, repulsive for antiparallel.',
      'Historically defined the ampere.',
      [['Wire 1 creates $B_1 = \\mu_0 I_1/(2\\pi d)$ at wire 2.', 'Long-wire result.'],
       ['Wire 2 (current $I_2$) feels $F/\\ell = I_2 B_1$.', '$\\vec F = I\\vec L\\times\\vec B$ with $\\sin 90° = 1$.'],
       ['Direction from RHR: parallel → attract, antiparallel → repel.', 'Cross product geometry.']],
      '\\frac{F}{\\ell} = \\frac{\\mu_0 I_1 I_2}{2\\pi d}',
      'Long parallel wires.'),
  ].join('');

  // ============= UNIT 13 — Induction =============
  DERIVATIONS['unit-13'] = [
    D('Faraday\'s law $\\varepsilon = -d\\Phi_B/dt$',
      'EMF around closed loop = negative rate of change of flux through it.',
      'Central law connecting changing $\\vec B$ to circuits.',
      [['EMF is $\\oint\\vec E\\cdot d\\vec l$ around the loop.', 'Work per unit charge around the loop.'],
       ['Experimentally: $\\varepsilon\\propto$ rate of flux change, with constant = 1 in SI.', 'From Faraday\'s original experiments.'],
       ['Minus sign: Lenz\'s law from energy conservation.', 'If induced current reinforced change, flux grows without external work — perpetual motion.']],
      '\\varepsilon = -\\frac{d\\Phi_B}{dt}',
      'Any closed loop (stationary or moving), any cause of flux change.'),

    D('Motional EMF $\\varepsilon = BLv$',
      'Rod of length $L$ moving at $v\\perp\\vec B$ develops $BLv$.',
      'Confirms Faraday from Lorentz force on carriers.',
      [['Carrier in rod moves at $v$ → magnetic force per charge = $v\\times B$, magnitude $vB$ along rod.', 'Lorentz force on free charges.'],
       ['Effective field $E_{eff} = vB$ along rod pushes charges to ends.', 'Until electrostatic field cancels it.'],
       ['EMF = work/charge along rod = $\\int(v\\times B)\\cdot d\\vec l = vBL$.', 'Uniform field, length $L$.'],
       ['Check: area grows at rate $Lv$, so $d\\Phi/dt = BLv$. ✓', 'Two derivations agree.']],
      '\\varepsilon = BLv',
      'Uniform $B\\perp v$ and rod; rod of length $L$.'),

    D('Self-inductance & back-EMF',
      'Flux linkage $N\\Phi = LI$; induced EMF $= -L\\,dI/dt$.',
      'Captures a circuit\'s ability to resist current changes.',
      [['Biot–Savart: $B\\propto I$, so $\\Phi\\propto I$.', 'Linearity in current.'],
       ['Total linkage $\\Lambda = N\\Phi = LI$; define $L = N\\Phi/I$.', '$L$ depends on geometry only.'],
       ['Faraday on coil: $\\varepsilon = -d\\Lambda/dt = -L\\,dI/dt$.', '$L$ constant.']],
      'L = \\frac{N\\Phi}{I},\\quad \\varepsilon = -L\\frac{dI}{dt}',
      'Rigid coil in linear medium.'),

    D('Solenoid inductance $L = \\mu_0 N^2 A/\\ell$',
      'Long solenoid self-inductance.',
      'Standard reference geometry.',
      [['Interior field: $B = \\mu_0 n I = \\mu_0(N/\\ell)I$.', 'Ampère.'],
       ['Flux per turn: $\\Phi = BA$.', 'Uniform inside.'],
       ['Linkage: $N\\Phi = \\mu_0 N^2 AI/\\ell$.', 'All turns share same flux.'],
       ['$L = N\\Phi/I = \\mu_0 N^2 A/\\ell$.', 'Geometric result.']],
      'L = \\frac{\\mu_0 N^2 A}{\\ell}',
      '$\\ell\\gg R$; tightly wound; air core.'),

    D('Energy in inductor $U = \\tfrac12 LI^2$',
      'Work against back-EMF builds up this field energy.',
      'Parallels capacitor energy.',
      [['Power against back-EMF: $P = \\varepsilon_L I = LI\\,dI/dt$.', 'Source pushes current against back-EMF.'],
       ['$U = \\int P\\,dt = \\int_0^I LI\'dI\' = \\tfrac12 LI^2$.', 'Change variable $t\\to I$.']],
      'U = \\tfrac12 LI^2',
      'Linear inductor; no dissipation during build-up.'),

    D('Magnetic energy density $u = B^2/(2\\mu_0)$',
      'Energy per unit volume in magnetic field.',
      'Localizes energy in the field.',
      [['Solenoid: $U = \\tfrac12 LI^2$ and $L = \\mu_0 N^2 A/\\ell$.', 'Known ingredients.'],
       ['$I = B\\ell/(\\mu_0 N)$; substitute to express $U$ via $B$.', 'Replace $I$ with $B$.'],
       ['$U = B^2 A\\ell/(2\\mu_0)$; divide by volume $A\\ell$.', 'Energy per volume.']],
      'u = \\frac{B^2}{2\\mu_0}',
      'Vacuum/linear medium.'),

    D('LR growth $I(t) = (\\varepsilon/R)(1 - e^{-Rt/L})$',
      'Current rises exponentially to $\\varepsilon/R$.',
      'Shows how inductance delays current.',
      [['KVL: $\\varepsilon - IR - L\\,dI/dt = 0$.', 'Sum of EMFs = sum of drops.'],
       ['Rearrange and separate: $dI/(\\varepsilon - IR) = dt/L$.', 'First-order ODE form.'],
       ['Integrate with $I(0)=0$: $-(1/R)\\ln(\\varepsilon - IR)|_0 = t/L$.', 'u-substitution.'],
       ['Exponentiate and solve: $I(t) = (\\varepsilon/R)(1 - e^{-Rt/L})$; $\\tau = L/R$.', 'Steady state $= \\varepsilon/R$ as $t\\to\\infty$.']],
      'I(t) = \\frac{\\varepsilon}{R}(1 - e^{-Rt/L}),\\quad \\tau = L/R',
      'Series LR, switch closed at $t=0$.'),

    D('LR decay $I(t) = I_0 e^{-Rt/L}$',
      'Current decays exponentially after source removed.',
      'Shows stored magnetic energy dissipates in $R$.',
      [['KVL no EMF: $L\\,dI/dt + IR = 0$.', 'Back-EMF drives current through $R$.'],
       ['Separate: $dI/I = -(R/L)dt$; integrate.', 'Linear first-order ODE.'],
       ['$I(t) = I_0 e^{-Rt/L}$.', '$I_0$ = current just before the switch change.']],
      'I(t) = I_0 e^{-Rt/L}',
      'Source removed at $t=0$; inductor had current $I_0$.'),
  ].join('');

  window.DERIVATIONS = DERIVATIONS;
})();
